export const MAP_DIALOGS = {
    "OPEN_MAP": "MAP_DIALOG",
    "CLOSE_MAP": "CLOSE_MAP_DIALOG",
    "ADD_MAP": "ADD_NEW_MAP",
    "REMOVE_MAP": "REMOVE_SELECTED_MAP",
    "OPEN_SEAT": "OPEN_SEAT_DIALOG",
    "CLOSE_SEAT": "CLOSE_SEAT_DIALOG",
    "ADD_SEAT": "ADD_SEAT_TO_MAP",
    "OPEN_BEACON": "OPEN_BEACON_DIALOG",
    "CLOSE_BEACON": "CLOSE_BEACON_DIALOG",
    "UPDATE_BEACON": "UPDATE_BEACON_DIALOG"
}
export const MAP_EVENTS = {
    "UPDATE_SEAT_GROUP": "UPDATE_SEAT_GROUP_COORDINATE",
    "ROTATE_SEAT_LEFT": "ROTATE_SELECTED_SEAT_LEFT",
    "ROTATE_SEAT_RIGHT": "ROTATE_SELECTED_SEAT_RIGHT",
    "CLEAR_SEATS": "CLEAR_SELECTED_SEATS",
    "REMOVE_SEATS": "REMOVE_SELECTED_SEATS"
}
export const MAP_CLICK = {
    "CLICK_SEAT": "SEAT_CLICKED",
    "CLICK_MAP": "MAP_CLICKED",
}

export const VIEW_MODE = {
    "Reserve": "RESERVESEAT",
    "Owner": "ADMIN"
}
export const MAP_BUILDER_HEIGHT = 500;

export const SEAT_SIZE = 65;