export const MAP_DIALOGS = {
    "OPEN_MAP": "MAP_DIALOG",
    "CLOSE_MAP": "CLOSE_MAP_DIALOG",
    "ADD_MAP": "ADD_NEW_MAP",
    "OPEN_SEAT": "OPEN_SEAT_DIALOG",
    "CLOSE_SEAT": "CLOSE_SEAT_DIALOG",
    "ADD_SEAT": "ADD_SEAT_TO_MAP"
}

export const MAP_BUILDER_HEIGHT = 500;

export const SEAT_SIZE = 60;